language: go

go:
  - 1.15.5

env:
  global:
    - IMAGE=vikings/golang
    - TAG=alpine

services:
  - docker

before_install:
  - echo "$DOCKERPASSWD" | docker login -u "$DOCKERUSER" --password-stdin registry.cn-hongkong.aliyuncs.com

install:
  - docker build -t registry.cn-hongkong.aliyuncs.com/$IMAGE:$TAG .

script:
  - echo "ignore go test command "

after_success:
  - docker push registry.cn-hongkong.aliyuncs.com/$IMAGE:$TAG

notifications:
  slack:
    rooms:
      - sync-from-docker-hub:5Q3mjXPHAuJ50LeUcUrfIWmx
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - "%{commit_message}"
      - "Result: %{result}"
  email:
    recipients:
      - ztao8607@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
