language: go

go:
  - 1.15.5

env:
  global:
    - IMAGE=redis
    - TAG=latest

services:
  - docker

before_install:
  - echo "$DOCKERPASSWD" | docker login -u "$DOCKERUSER" --password-stdin registry.cn-hongkong.aliyuncs.com

install:
  - docker build -t registry.cn-hongkong.aliyuncs.com/sync-hub-docker/$IMAGE:$TAG .

script:
  - echo "ignore go test command "

after_success:
  - docker push registry.cn-hongkong.aliyuncs.com/sync-hub-docker/$IMAGE:$TAG

notifications:
  email:
    recipients:
      - ztao8607@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
